# Generated by Django 5.0.6 on 2024-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypmd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("popularity", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("country", "name", "artist")},
            },
        ),
    ]
