# Generated by Django 5.0.6 on 2024-09-14 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mypmd", "0002_musicchart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MusicChart",
        ),
    ]
